using System.Reflection;
using System.Text;

var options = Arguments.Parse(args);
var model = Assembly.LoadFrom(options.Model);
ValidateContract(model);
var generated = Render(model.GetName().Version?.ToString() ?? "unknown");

if (options.Check)
{
    if (!File.Exists(options.Output) || File.ReadAllText(options.Output) != generated)
        throw new InvalidOperationException("Generated protocol DTOs differ. Run the generator without --check and commit the result.");
    return;
}

Directory.CreateDirectory(Path.GetDirectoryName(options.Output)!);
File.WriteAllText(options.Output, generated, new UTF8Encoding(false));

static void ValidateContract(Assembly model)
{
    foreach (var name in new[]
    {
        "Voxta.Model.WebsocketMessages.ClientMessages.ClientAuthenticateMessage",
        "Voxta.Model.WebsocketMessages.ClientMessages.ClientStartChatMessage",
        "Voxta.Model.WebsocketMessages.ClientMessages.ClientSendMessage",
        "Voxta.Model.WebsocketMessages.ClientMessages.ClientInterruptMessage",
        "Voxta.Model.WebsocketMessages.ClientMessages.ClientSpeechPlaybackStartMessage",
        "Voxta.Model.WebsocketMessages.ClientMessages.ClientSpeechPlaybackCompleteMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerWelcomeMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerChatStartedMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerReplyStartMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerReplyChunkMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerReplyEndMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerSpeechPlaybackStartMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerSpeechPlaybackCompleteMessage",
        "Voxta.Model.WebsocketMessages.ServerMessages.ServerInterruptSpeechMessage"
        ,"Voxta.Model.WebsocketMessages.ServerMessages.ServerRecordingRequestMessage"
        ,"Voxta.Model.WebsocketMessages.ServerMessages.ServerSpeechRecognitionStartMessage"
        ,"Voxta.Model.WebsocketMessages.ServerMessages.ServerSpeechRecognitionPartialMessage"
        ,"Voxta.Model.WebsocketMessages.ServerMessages.ServerSpeechRecognitionEndMessage"
        ,"Voxta.Model.WebsocketMessages.ServerMessages.ServerAudioFrameMessage"
    })
        if (model.GetType(name) is null) throw new InvalidOperationException($"Pinned Voxta.Model is missing {name}.");
}

static string Render(string modelVersion) => $$"""
// <auto-generated />
// Generated by Tools/ProtocolGenerator from pinned Voxta.Model commit b533b287194af6fc418900d1384fb2fda2f7d286 (assembly {{modelVersion}}). Do not edit.
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
namespace Voxta.Unity.Protocol.Generated {
 [Serializable] public abstract class ClientMessage { }
 [Serializable] public abstract class ServerMessage { }
 [Serializable] public abstract class ClientChatSessionMessage : ClientMessage { public Guid SessionId { get; set; } }
 [Serializable] public abstract class ServerChatSessionMessage : ServerMessage { public Guid SessionId { get; set; } }
 [Serializable] public sealed class ClientAuthenticateMessage : ClientMessage { public string Client { get; set; } public string ClientVersion { get; set; } public string[] Scope { get; set; } = new[] { "role:app" }; public ClientCapabilities Capabilities { get; set; } = new ClientCapabilities(); }
 [Serializable] public sealed class ClientCapabilities { public AudioInputClientCapabilities AudioInput { get; set; } = AudioInputClientCapabilities.None; public AudioOutputClientCapabilities AudioOutput { get; set; } = AudioOutputClientCapabilities.None; public string[] AcceptedAudioContentTypes { get; set; } = new[] { "audio/x-wav" }; public VisionCaptureClientCapabilities VisionCapture { get; set; } = VisionCaptureClientCapabilities.None; public string[] Features { get; set; } = Array.Empty<string>(); }
 public enum AudioInputClientCapabilities { None, WebSocketStream } public enum AudioOutputClientCapabilities { None, Url, LocalFile } public enum VisionCaptureClientCapabilities { None, PostImage }
 [Serializable] public sealed class ClientStartChatMessage : ClientMessage { public Guid? ChatId { get; set; } public Guid? CharacterId { get; set; } public Guid? ScenarioId { get; set; } public bool Ephemeral { get; set; } public string Title { get; set; } public string[] DisableServices { get; set; } }
 [Serializable] public sealed class ClientSendMessage : ClientChatSessionMessage { public string Text { get; set; } public bool DoContinue { get; set; } = true; public bool DoReply { get; set; } = true; public ChatMessageRole Role { get; set; } = ChatMessageRole.User; }
 [Serializable] public sealed class ClientInterruptMessage : ClientChatSessionMessage { }
 [Serializable] public sealed class ClientSpeechPlaybackStartMessage : ClientChatSessionMessage { public Guid MessageId { get; set; } public int StartIndex { get; set; } public int EndIndex { get; set; } public double Duration { get; set; } public bool IsNarration { get; set; } }
 [Serializable] public sealed class ClientSpeechPlaybackCompleteMessage : ClientChatSessionMessage { public Guid MessageId { get; set; } }
 public enum ChatMessageRole { Undefined = 0, System = 1, Assistant = 2, User = 3, Summary = 4, Event = 5, Instructions = 6, Note = 7, Secret = 8, Infer = 9, Tool = 10 }
 [Serializable] public sealed class ServerWelcomeMessage : ServerMessage { public string VoxtaServerVersion { get; set; } public string VoxtaServerCommit { get; set; } public string ApiVersion { get; set; } public string RegisteredClientVersion { get; set; } public ChatParticipantInfo User { get; set; } }
 [Serializable] public sealed class ServerAuthenticationRequiredMessage : ServerMessage { }
 [Serializable] public sealed class ServerErrorMessage : ServerMessage { public string Message { get; set; } public string Details { get; set; } }
 [Serializable] public sealed class ServerChatStartingMessage : ServerChatSessionMessage { public Guid ChatId { get; set; } public string Title { get; set; } }
 [Serializable] public sealed class ServerChatStartedMessage : ServerChatSessionMessage { public Guid ChatId { get; set; } public string Title { get; set; } public ChatMessage[] Messages { get; set; } = Array.Empty<ChatMessage>(); }
 [Serializable] public sealed class ServerReplyStartMessage : ServerChatSessionMessage { public Guid MessageId { get; set; } public Guid SenderId { get; set; } public long ChatTime { get; set; } }
 [Serializable] public sealed class ServerReplyChunkMessage : ServerChatSessionMessage { public Guid MessageId { get; set; } public Guid SenderId { get; set; } public int StartIndex { get; set; } public int EndIndex { get; set; } public string Text { get; set; } public string AudioUrl { get; set; } public bool IsNarration { get; set; } public int? AudioGapMs { get; set; } public string Affect { get; set; } public bool AffectCarried { get; set; } }
 [Serializable] public sealed class ServerReplyEndMessage : ServerChatSessionMessage { public Guid MessageId { get; set; } public Guid SenderId { get; set; } public int Tokens { get; set; } }
 [Serializable] public sealed class ServerSpeechPlaybackStartMessage : ServerChatSessionMessage { public Guid MessageId { get; set; } public int StartIndex { get; set; } public double Duration { get; set; } }
 [Serializable] public sealed class ServerSpeechPlaybackCompleteMessage : ServerChatSessionMessage { public Guid MessageId { get; set; } }
 [Serializable] public sealed class ServerInterruptSpeechMessage : ServerChatSessionMessage { public Guid MessageId { get; set; } }
 [Serializable] public sealed class ServerRecordingRequestMessage : ServerMessage { public Guid SessionId { get; set; } public bool Enabled { get; set; } }
 [Serializable] public sealed class ServerSpeechRecognitionStartMessage : ServerMessage { }
 [Serializable] public sealed class ServerSpeechRecognitionPartialMessage : ServerMessage { public string Text { get; set; } }
 [Serializable] public sealed class ServerSpeechRecognitionEndMessage : ServerMessage { public string Text { get; set; } public string Reason { get; set; } public TranscriptWordInfo[] Words { get; set; } public double DoubtfulConfidence { get; set; } public double UnusableConfidence { get; set; } public TranscriptRepairInfo Repair { get; set; } public bool MisheardWordsEnabled { get; set; } public string MisheardWordsSuppression { get; set; } }
 [Serializable] public sealed class TranscriptWordInfo { public string Text { get; set; } public double? Confidence { get; set; } }
 [Serializable] public sealed class TranscriptRepairInfo { public string Action { get; set; } public string[] DoubtfulWords { get; set; } }
 [Serializable] public sealed class ServerAudioFrameMessage : ServerMessage { public float Rms { get; set; } public bool VoiceActivity { get; set; } public bool Listening { get; set; } public float? NoiseFloorRms { get; set; } public float? ThresholdRms { get; set; } public bool? RunHeldOpen { get; set; } }
 [Serializable] public sealed class ChatParticipantInfo { public Guid Id { get; set; } public string Name { get; set; } public string ThumbnailUrl { get; set; } }
 [Serializable] public sealed class ChatMessage { public Guid MessageId { get; set; } public ChatMessageRole Role { get; set; } public Guid SenderId { get; set; } public string Name { get; set; } public string Text { get; set; } public DateTimeOffset Timestamp { get; set; } }
 public static class VoxtaJson { public static JsonSerializerOptions CreateOptions() { var o = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull }; var b = new JsonSerializerOptions(o); o.Converters.Add(new ClientMessageConverterFactory(b)); o.Converters.Add(new ServerMessageConverter(b)); return o; } }
 internal sealed class ClientMessageConverterFactory : JsonConverterFactory { readonly JsonSerializerOptions o; internal ClientMessageConverterFactory(JsonSerializerOptions o) { this.o=o; } public override bool CanConvert(Type t) { return typeof(ClientMessage).IsAssignableFrom(t); } public override JsonConverter CreateConverter(Type t, JsonSerializerOptions s) { return (JsonConverter)Activator.CreateInstance(typeof(ClientMessageConverter<>).MakeGenericType(t),o); } }
 internal sealed class ClientMessageConverter<T> : JsonConverter<T> where T : ClientMessage { readonly JsonSerializerOptions o; public ClientMessageConverter(JsonSerializerOptions o) { this.o=o; } public override T Read(ref Utf8JsonReader r, Type t, JsonSerializerOptions s) { throw new JsonException("Client messages are send-only."); } public override void Write(Utf8JsonWriter w, T v, JsonSerializerOptions s) { M1Json.Write(w,v,v is ClientAuthenticateMessage ? "authenticate" : v is ClientStartChatMessage ? "startChat" : v is ClientSendMessage ? "send" : v is ClientInterruptMessage ? "interrupt" : v is ClientSpeechPlaybackStartMessage ? "speechPlaybackStart" : v is ClientSpeechPlaybackCompleteMessage ? "speechPlaybackComplete" : throw new JsonException("Unsupported Voxta M3 client message."),o); } }
 internal sealed class ServerMessageConverter : JsonConverter<ServerMessage> { readonly JsonSerializerOptions o; internal ServerMessageConverter(JsonSerializerOptions o) { this.o=o; } public override ServerMessage Read(ref Utf8JsonReader r, Type t, JsonSerializerOptions s) { using(var d=JsonDocument.ParseValue(ref r)) { if(!d.RootElement.TryGetProperty("$type",out var k)) throw new JsonException("Voxta message has no $type."); var x=k.GetString(); Type target=x=="welcome"?typeof(ServerWelcomeMessage):x=="authenticationRequired"?typeof(ServerAuthenticationRequiredMessage):x=="error"?typeof(ServerErrorMessage):x=="chatStarting"?typeof(ServerChatStartingMessage):x=="chatStarted"?typeof(ServerChatStartedMessage):x=="replyStart"?typeof(ServerReplyStartMessage):x=="replyChunk"?typeof(ServerReplyChunkMessage):x=="replyEnd"?typeof(ServerReplyEndMessage):x=="speechPlaybackStart"?typeof(ServerSpeechPlaybackStartMessage):x=="speechPlaybackComplete"?typeof(ServerSpeechPlaybackCompleteMessage):x=="interruptSpeech"?typeof(ServerInterruptSpeechMessage):x=="recordingRequest"?typeof(ServerRecordingRequestMessage):x=="speechRecognitionStart"?typeof(ServerSpeechRecognitionStartMessage):x=="speechRecognitionPartial"?typeof(ServerSpeechRecognitionPartialMessage):x=="speechRecognitionEnd"?typeof(ServerSpeechRecognitionEndMessage):x=="audioFrame"?typeof(ServerAudioFrameMessage):throw new JsonException("Unsupported Voxta M3 message type: "+x); return (ServerMessage)JsonSerializer.Deserialize(d.RootElement.GetRawText(),target,o); } } public override void Write(Utf8JsonWriter w, ServerMessage v, JsonSerializerOptions s) { throw new JsonException("Server messages are receive-only."); } }
 internal static class M1Json { internal static void Write(Utf8JsonWriter w, object v, string t, JsonSerializerOptions o) { var e=JsonSerializer.SerializeToElement(v,v.GetType(),o); w.WriteStartObject(); w.WriteString("$type",t); foreach(var p in e.EnumerateObject()) p.WriteTo(w); w.WriteEndObject(); } }
}
""";

sealed record Arguments(string Model, string Output, bool Check)
{
    public static Arguments Parse(string[] args)
    {
        string Value(string key) { var i = Array.IndexOf(args, key); return i >= 0 && i + 1 < args.Length ? args[i + 1] : throw new ArgumentException($"Missing {key}."); }
        return new Arguments(Value("--model"), Value("--output"), args.Contains("--check"));
    }
}
